# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0002_auto_20160311_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklisteddomain',
            options={'ordering': ('domain',)},
        ),
    ]
