# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0003_auto_20160311_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTarget',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
    ]
